accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name= 'accounts'

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('/todo/')),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('todo/', include("todo_app.urls")),
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'todo_app'

urlpatterns = [
    path('', views.HomeView.as_view(), name= 'home'),
    path('create/', views.TaskCreateView.as_view(), name= 'create'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name= 'delete'),
    path('done/', views.TaskDoneView.as_view(), name= 'task_done'),
    path('done/<int:pk>/', views.MarkChangeView.as_view(), name= 'mark_ch'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    # AbstractUserのうちカスタマイズするものだけを以下に指定する
    # メールアドレスはデフォルトでnullはOK、他ユーザーとの重複もOKになっているためカスタマイズする
    # yunique=Trueにすると重複できないし、nullにもできなくなる。
    email = models.EmailField('メールアドレス', default=None)

todo_app/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Tasks(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    task_title = models.CharField(max_length=64)
    task_due = models.DateTimeField(verbose_name='Due Date',null=True)
    is_finished = models.BooleanField(default=False)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    
    def __str__(self):
        return self.task_title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()


# UserCreationFormはDjangoが元々用意している新規登録用のフォーム
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")
    
    # このsaveはformのsave。フォームを投稿した時にこのsaveが呼ばれる
    def save(self):
        
        user = super().save()
        user.save()   # このsaveはmodelのsave。これでデータベースに書き込める
        return user
    

class LoginFrom(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password1",)

accounts/views.py
from django.shortcuts import render,redirect
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

from .forms import SignUpForm, LoginFrom

# class SignUpView(CreateView):
#     form_class = SignUpForm
#     success_url = reverse_lazy('accounts:login')
#     template_name = 'signup.html'

class SignUpView(CreateView):
    template_name = 'signup.html'
    form_class =SignUpForm

    def form_valid(self, form):
        user = form.save() # formの情報を保存
        return redirect('accounts:login')

    # データ送信
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Sign up"
        return context

class LoginView(LoginView):
    form_class = LoginFrom
    template_name = "login.html"

class LogoutView(LogoutView):
    success_url = reverse_lazy('todo_app:home')

todo_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, UpdateView
from django.shortcuts import HttpResponseRedirect
from django.http import HttpResponse

from .models import Tasks
from .form import TaskCreationForm

# def homepage(request):
#     return render(request, 'home.html')

class HomeView(ListView):
    template_name = 'home.html'
    context_object_name = 'tasks'
    
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            return Tasks.objects.filter(user=user, is_finished=False).order_by('-created_at')
        else:
            return Tasks.objects.none()
    
class TaskCreateView(CreateView):
    model = Tasks
    form_class = TaskCreationForm
    template_name = 'create_task.html'
    success_url = reverse_lazy('todo_app:home')

    def form_valid(self, form):
        pd = form.save(commit=False)
        pd.user = self.request.user
        pd.save()
        return super().form_valid(form)
    
class TaskDeleteView(DeleteView):
    model = Tasks
    template_name = 'delete.html'
    success_url = reverse_lazy('todo_app:task_done')

    def get(self, request, *args, **kwargs):
        # オブジェクトを取得して削除
        self.object = self.get_object()
        self.object.delete()

        return HttpResponseRedirect(self.get_success_url())
    
class MarkChangeView(UpdateView):
    model = Tasks
    fields = ['is_finished']
    template_name = 'mark_ch.html'
    success_url = reverse_lazy('todo_app:home')

    def post(self, request, *args, **kwargs):
        # task = self.get_object()
        # if 'is_finished' in request.POST:
        #     task.is_finished = True
        #     task.save()
        task = self.get_object()
        print(task)
        if 'is_finished' in request.POST:
            task.is_finished = request.POST['is_finished']
            task.save()
        return HttpResponseRedirect(self.success_url)

class TaskDoneView(ListView):
    template_name = 'task_done.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            return Tasks.objects.filter(user=user, is_finished=True)
        else:
            return Tasks.objects.none()

accounts/templates/login.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<header>
    <nav class="p-4 bg-emerald-500 ">
        <a class="text-white text-2xl italic" aria-current="page">todo</a>
    </nav>
</header>

<body>
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="254" required="" id="id_username" value="" placeholder="Username">
        {{ field.label }}
        {{ field }}
        {{ field.errors }}
        <br>
        <input type="password" name="password" autocomplete="current-password" required="" id="id_password" value="" placeholder="Password">
        <div class="mt-3">
                <button type="submit" >Login</button>
                <a href="{% url 'todo_app:home' %}" >Back</a>
        </div>
    </form>
    <a href="{% url 'accounts:signup' %}" >アカウントをお持ちでない方はこちら</a>
</body>
</html>

accounts/templates/logout.html
<body>
    <div class = 'logout'>
        <h3 class="mt-4 mb-4" style = 'color: red;'>ログアウトしました</h3>
        <a class = ' text-sky-500' href = '{% url "todo_app:home" %}'>トップページへ</a>
    </div>
</body>

accounts/templates/signup.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<header>
    <nav class="p-4 bg-emerald-500 ">
        <a class="text-white text-2xl italic" aria-current="page">todo</a>
    </nav>
</header>
<body class="">

    <h1>Sign up</h1>

    <form method="POST">
        {% csrf_token %}
        <div>
            {{ form.username }}
        </div>
        <div>
            {{ form.password1 }}
            {{ form.password2 }}
        </div>
        {{ from.errors }}
        <button type="submit">決定</button>
    </form>
</body>
<style>
    input{
        border: 1px black solid
    }
</style>
</html>

todo_app/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        {% if user.is_authenticated %}
        <nav class="p-3 bg-emerald-500 flex flex justify-between items-center">
            <div>
                <a class="text-white text-2xl italic" aria-current="page">todo</a>
                <div class="text-white">
                {{ user.username }} でログイン中
                </div>
                <form action='{% url "accounts:logout" %}' method='post' name='logout'>
                {% csrf_token %}
                <!-- <button type="submit">ログアウト</button> -->
                    <input type="submit" class="text-violet-500 ml-4" value="ログアウト">
                </form>
            </div>
            <div>
                <a class="text-white" href="{% url 'todo_app:home' %}">ホーム</a>
            </div>
            <div>
                <a class="text-white" href="{% url 'todo_app:create' %}">タスク作成</a>
            </div>
            <div>
                <a class="text-white" href="{% url 'todo_app:task_done' %}">完了済みタスク</a>
            </div>
            
        </nav>


        {% else %}
        <nav class="p-4 bg-emerald-500 ">
            <a class="text-white text-2xl italic" aria-current="page">todo</a>
            <a class="ml-4 text-white" aria-current="page" href="{% url 'accounts:signup' %}">登録</a>
            <a class="text-white ml-4" aria-current="page" href="{% url 'accounts:login' %}">ログイン</a>
        </nav>

        {% endif %}
        </nav>
</header>
<main>{% block contents %}{% endblock %}</main>
</body>
</html>

todo_app/templates/create_task.html
{% extends 'base.html'%}
{% load static %}


{% block contents %}
<div class="flex flex-col justify-center items-center w-30">
    <div class="text-3xl">
    タスク作成
    </div>
    <form method="post">
    {% csrf_token %}
        <div>内容を入力して下さい:
        {{ form.task_title }}
        </div>
        <div>期限を入力して下さい:
        {{ form.task_due }}
        </div>
        <button type="submit" class="" >決定</button>
    </form>
</div>


{% endblock %}

todo_app/templates/delete.html
<body>
    <div class = 'logout'>
        <h3 class="mt-4 mb-4" style = 'color: red;'>削除しました</h3>
        <a class = ' text-sky-500' href = '{% url "todo_app:home" %}'>トップページへ</a>
    </div>
</body>

todo_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}
<div class="flex flex-col justify-center items-center w-30">
    <div class="mt-6">
        {% if user.is_authenticated %}
        <div class="text-3xl">
            やるべきことリスト!!
        </div>
        {% if tasks %}
        <div class="mt-10">
            {% for task in tasks %}
            <div class="mt-4 ">
                <div class="flex justify-between">
                    <div class="text-2xl">
                        {{ task.task_title }}
                    </div>
                    <!-- <a href = '{% url "todo_app:delete" task.id %}' class="bg-orange-600 p-1 text-white" onclick="return alertFunc();">タスク完了</a> -->
                    <form method="post" action="{% url 'todo_app:mark_ch' task.id %}" onsubmit="return validateForm(this);">
                        {% csrf_token %}
                        <input type="checkbox" name="is_finished" value="True" id="is_finished_{{ task.id }}">
                        <button type="submit"  class="bg-orange-600 p-1 text-white">タスク完了</button>
                    </form>
                </div>
                <!-- <script>
                    function alertFunc() {
                        var del = confirm("本当に削除しますか？");
                        if (del == true) {
                            return true;
                        } else {
                            location.href = '{% url "todo_app:home" %}';
                            return false;
                        }
                    }
                </script> -->
                <script>
                    function validateForm(form) {
                        var checkbox = form.querySelector('input[name="is_finished"]');
                        if (!checkbox.checked) {
                            alert("チェックボックスを入力してください");
                            return false;
                        }
                        // return confirm("本当に削除しますか？");
                    }
                    </script>
                <div class="flex text-xl">
                    <div class="ml-2 ">
                        期限：　{{ task.task_due }}
                    </div>
            </div>
            {% endfor %}
        </div>
        
        {% else %}
        <div>
            タスクはありません。
        </div>
        {% endif %}
        {% else %}
        <div class="flex flex-col text-center">
            <p class="text-3xl">ようこそtodoアプリへ!</p>
            <p class="mt-10">現在はログアウトしています</p>
        </div>
        
        {% endif %}
    </div>
</div>
{% if user.is_authenticated %}
<div class="fixed">
    <a href="{% url 'todo_app:create' %}" id="plus_btn" >＋</a>
</div>
{% endif %}
{% endblock %}

todo_app/templates/mark_ch.html
{% extends 'base.html'%}


{% block contents %}
<div class="flex flex-col justify-center items-center w-30">
    <h1>Mark Task Done</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="is_finished" value="true">
        <button type="submit">タスク完了</button>
    </form>
    <a href="{% url 'todo_app:home' %}">未完了のタスクに戻る</a>
</div>

{% endblock %}

todo_app/templates/mark_done.html
{% extends 'base.html'%}


{% block contents %}
<div class="flex flex-col justify-center items-center w-30">
    <h1>Mark Task Done</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="is_finished" value="true">
        <button type="submit">タスク完了</button>
    </form>
    <a href="{% url 'todo_app:home' %}">未完了のタスクに戻る</a>
</div>

{% endblock %}

todo_app/templates/task_done.html
{% extends 'base.html'%}


{% block contents %}
<div class="flex flex-col justify-center items-center w-30">
    <div class="text-3xl mt-10">
        完了したタスク
    </div>
    {% if tasks %}
    <div class="mt-10">
        {% for task in tasks %}
        <div class="mt-4 ">
            <div class="flex justify-between">
                <div class="text-2xl">
                    {{ task.task_title }}
                </div>
                <div class="flex end">
                    <form method="post" action="{% url 'todo_app:mark_ch' task.id %}" class="mr-4">
                        {% csrf_token %}
                        <input type="hidden" name="is_finished" value="False">
                        <button type="submit" class="bg-lime-500 p-1 text-white">復元</button>
                    </form>
                <!-- <a href = '{% url "todo_app:delete" task.id %}' class="bg-orange-600 p-1 text-white" onclick="return alertFunc();">タスク完了</a> -->
                    <form method="post" action="{% url 'todo_app:delete' task.id %}">
                        {% csrf_token %}
                        <button type="submit" onclick="return alertFunc();" class="bg-red-600 p-1 text-white">削除</button>
                    </form>
                </div>
                
            </div>
            <script>
                function alertFunc() {
                    const del = confirm("本当に削除しますか？");
                    if (del == true) {
                        return true;
                    } else {
                        location.href = '{% url "todo_app:task_done" %}';
                        return false;
                    }
                }
            </script>
            <div class="flex text-xl">
                <div class="ml-2 ">
                    期限：　{{ task.task_due }}
                </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div>完了したタスクはありません</div>
    {% endif %}
</div>

{% endblock %}